### ISSUE TITLE
CORB blocking on chrome

### ISSUE THREAD

**Issue by croustibat** [lyra/embedded-form-glue#10]
Hello,

I've got this issue on chrome dev tools when loading the form on a React (CRA) App : 
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response 
https://sentry.lyra-network.com/api/2/store/sentry_key=xxx&sentry_version=7 
with MIME type application/json. 
See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

Not sure how to deal with that, do you have an idea ?

**Comment by yyoyo** [comment]
Hi.

Sorry but the Lyra javascript library has an issue with the embedded-form-glue component. Fixed version will be published next week.

Sorry for that,
Lionel.

**Comment by croustibat** [comment]
Hi, 

I'm looking forward to get the fix.

Thank you.

**Comment by croustibat** [comment]
Hello, 

do you manage to fix it ?

**Comment by yyoyo** [comment]
Hi.

We are late, we found more bugs :(.

it will be published next week. I'll contact you privately to give you a temporary URL.

**Comment by yyoyo** [comment]
Hi,

The transaction has been published on public URLs.

Thanks for your patience,
Lionel.
