### ISSUE TITLE
How to customize form wih React ?

### ISSUE THREAD

**Issue by Robilol** [lyra/embedded-form-glue#144]
I'm trying with React to customize my form but it doesn't seem to work. 
Payzen form is added after my custom form.

```js
useEffect(() => {
    const endpoint = 'https://api.payzen.eu/api-payment/V4/'
    const publicKey = 'xxxxx'
    const formToken = 'xxxxx'

    KRGlue.loadLibrary(endpoint, publicKey) /* Load the remote library */
      .then(({ KR }) => {
        console.log(KR)

        return KR.setFormConfig({
          /* set the minimal configuration */
          formToken: formToken,
          'kr-language': 'en-US' /* to update initialization parameter */,
        })
      })
      .then(({ KR }) => KR.attachForm('#payzenForm')) /* add a payment form  to myPaymentForm div*/
      .then(({ KR, result }) => KR.showForm(result.formId)) /* show the payment form */
  }, [])


return (
  <div
    id="payzenForm"
    style={{
      display: selectedCard ? 'none' : 'block',
    }}
  >
    <div className="bg-primary p-default">
      <span>test</span>
      <div className="kr-pan"></div>
    </div>
    <div className="kr-expiry"></div>
    <h1>test</h1>
    <div className="bg-primary p-default">
      <span>test</span>
      <div className="kr-security-code"></div>
    </div>
  
    <button className="kr-payment-button"></button>
  
    <div className="kr-form-error"></div>
  </div>
)
```
![image](https://user-images.githubusercontent.com/23209925/133396167-e07be387-26d1-4d84-8876-ac2bff8cb21a.png)

Have I miss something ?

**Comment by s-yagues** [comment]
Hi @Robilol ,

For the attachForm method, the DOM element used needs to have the element `.kr-embedded` as a child if you want to add extra elements to the form. If it doesn't have this element inside, it will add a `.kr-embedded` element at the end of `#payzenForm` with the form inside.

Here you can find your example modified:
https://codesandbox.io/s/embeddedformglue-react-attachform-eg0ev?file=/src/App.js

We'll improve our documentation in the next weeks to explain better all these use cases.

**Comment by Robilol** [comment]
I have tried to set the class on my parent div. I didn't understand that it should be a child.

thank you so much !
