### ISSUE TITLE
Angular : KRGlue imported object is empty

### ISSUE THREAD

**Issue by hms4242** [lyra/embedded-form-glue#15]
Hi, 
 When trying the basic example documented in Angular example readme, **from scratch (not inside current project)**, I get an arror stating that `KRGlue.loadLibrary is undefined`. It seems that KRGlue is actually an empty object. My guess is that `dist` directory should contain a `.d.ts` (typescript declaration file) so the object can be correctly imported into an Angular project. Note : for some reason, directly building the Angular app inside this project doesn't lead to any error so this is not a way to reproduce the current error.

**Comment by loic-couharde** [comment]
Hi,
Same thing in my React project, `import KRGlue from '@lyracom/embedded-form-glue';` return an empty object.
Tell me if you need more informations or any help for testing.

**Comment by yyoyo** [comment]
I'll check and I will let you know.

thanks.

**Comment by yyoyo** [comment]
Please could you try with the last version ? (0.2.5)

thanks,
Lionel.

**Comment by loic-couharde** [comment]
It's working for me on version 0.2.5, Thanks.

**Comment by hms4242** [comment]
Yes! working for me too! Thanks!
