### ISSUE TITLE
Is there a way to cleanup the library after the payment is done ?

### ISSUE THREAD

**Issue by vodkapomme** [lyra/embedded-form-glue#157]
Hello,

Is there a way to properly clean the library when the payment is done ? 

We are in a SPA scenario and we would like to clean all the things created by the library (like windows.KR* or the test card bottom bar even if it's not enabled in prod) after the payment is done

Those things are created outside React and we would like to handle component unmounting properly

I tried to get through the payzen JS Reference documentation and through this repository but i didn't found a "cleanup" method

Many Thanks

Jonathan

**Comment by s-yagues** [comment]
Hi @vodkapomme , 

Thanks for writing in. We have a method to clean the current initialized forms:

```javascript
await KR.removeForms()
```

This method will clean all related DOM elements and data from initialized form. After that, you can generate the form again with the same method you used the first time.

We are working on improving our documentation and add these missing methods.

**Comment by vodkapomme** [comment]
Hi @s-yagues, at first glance i thought that this method was only removing the forms (as the name tells) but it does exactly what i needed !

Many thanks and have a nice day :)
