### ISSUE TITLE
Apply different css style for each tab in the lyra form

### ISSUE THREAD

**Issue by NigsonNeves** [lyra/embedded-form-glue#167]
Hi,

I'm actually running into a problem, I would like to apply different css style for each tab (Saved cards and New card) in the lyra form but I can't find a way of doing it. Is it possible to achieve this ?

Thanks you for your answer :)

**Comment by s-yagues** [comment]
Hi @NigsonNeves ,

Thanks for writing in. You should be able to do it using the classes `kr-wallet-newcard` and `kr-wallet-mycards` in the `kr-embedded` element. These classes are automatically added when the form is rendered in **wallet** mode.

`<div class="kr-embedded kr-wallet-newcard"></div>`

`<div class="kr-embedded kr-wallet-mycards"></div>`

**Comment by NigsonNeves** [comment]
Hi @s-yagues ,

Thank you very much for your answer.

Does it changes the style content of this tab ? Because what i'm trying to achieve is having different style for each content of those tabs not only the tab itself.

**Comment by s-yagues** [comment]
@NigsonNeves Yes, these classes are on the parent element and each one is added or removed depending on which tab is active, so by using them, you should be able to apply different styles to the tabs and also the content for each tab.

**Comment by NigsonNeves** [comment]
@s-yagues 

Is it possible to have an exemple HTML/CSS? (Sorry, I'm a bit confused on how to proceed)

**Comment by NigsonNeves** [comment]
@s-yagues 

Thank you very much for your help, I manage to resolve my problem with your help :)

I may have a last question, is it possible to change the icons, like the delete button ?

**Comment by s-yagues** [comment]
Hi @NigsonNeves ,

Great, glad to read that!

I'm afraid there is no way right now to modify the order of this elements. The HTML structure of the card list is not customizable, but we'll take it into consideration for future versions.

**Comment by NigsonNeves** [comment]
@s-yagues 

No problem, thank you very much for your help.
Keep up the good work ;)
