### ISSUE TITLE
Angular integration : KR.onSubmit doesnt catch failure responses

### ISSUE THREAD

**Issue by hms4242** [lyra/embedded-form-glue#17]
Hi, 
 When using onSubmit for catching payment response in an Angular app, it looks like failure responses (payment not accepted etc) are not catched by this method (the method is not called at all). Can you help me on that?
Thanks.

**Comment by yyoyo** [comment]
Hi.
that's true.

KR.onSumbit() is called only when the transaction is accepted.
To catch errors when transactions are refused, or any payment form errors, you should use onError() like:

```javascript
KR.onError( function(event) {
            var code = event.errorCode;
            var message = event.errorMessage;
            var myMessage = code + ": " + message;

            $("#customerror").html(myMessage);
          });
```

**Comment by hms4242** [comment]
Thanks for answering, `onError` does the job. Thanks!
