### ISSUE TITLE
[Question] How to handle installment payments?

### ISSUE THREAD

**Issue by whygee-dev** [lyra/embedded-form-glue#192]
Hello,

I've been looking around through the docs but I can't figure out how to let the buyer choose the installment number. I tried passing this to the CreatePayment endpoint

``` 
transactionOption: {
   cardOptions: {
      installmentNumber: 3,
   },
}
```

but it doesn't do much.

I also saw that there is config relative to installment payments

```
 /**
     * @summary Installments field content label (singular)
     */
     'kr-installments-label-singular'?: string;
    /**
     * @summary Installments field content label (plural)
     */
     'kr-installments-label-plural'?: string;
     ....
```
I have no idea how they are used though

Any help is very much appreciated, thank you.

**Comment by cbrunielyra** [comment]
Hi, you can configure your installments in your Back Office in Settings>Company>Payment Options. You will be able to add installments only on contract that support it.

I have updated documentation for types. These methods can ce used when you want to customize installments labels
