### ISSUE TITLE
Example for openPopin

### ISSUE THREAD

**Issue by HUANGManutea** [lyra/embedded-form-glue#201]
Hi, I try to open the form in a popin.

In the file index.d.ts there is this function:
`openPopin: (formId: string) => Promise<{ KR: KR }>;`

Do you have an example of code with this function?

Best regards,

**Comment by s-yagues** [comment]
Hi @HUANGManutea ,

Thanks for reaching in. Here an example of how to use `openPopin` method:

```javascript
// The formId is optional
KR.openPopin(formId).then({KR} => {
 // After opening actions....
}).catch()
```
With async/await
```javascript
await KR.openPopin()
```

**Comment by HUANGManutea** [comment]
@s-yagues Thank you fo your answer, but I fail to understand when should I call it, I tried this code, based on the angular example, but nothing happens (I correctly got the formToken) :
`
KRGlue.loadLibrary(endpoint, publicKey) /* Load the remote library */
      .then( ({ KR }) =>
        KR.setFormConfig({
          /* set the minimal configuration */
          formToken: formTokenResponse.formToken,
          "kr-language": "fr-FR" /* to update initialization parameter */
        })
      )
      .then(({ KR }) =>
        KR.openPopin("#myPaymentForm")
      ) /* show the payment form */
      .then( ({ KR }) => KR.onSubmit(response => this.showPaid(response)))
`
the associated html is:
`
  <h1>Form 2</h1>
  <div class="container">
    <div id="myPaymentForm"></div>
  </div>
`
Do you have a suggestion?

**Comment by s-yagues** [comment]
Hi @HUANGManutea ,

It looks like you need to add the Form before trying to open it. e.g:

```javascript
KRGlue.loadLibrary(endpoint, publicKey) /* Load the remote library */
      .then( ({ KR }) =>
        KR.setFormConfig({
          formToken: formTokenResponse.formToken,
          "kr-language": "fr-FR",
          'kr-popin': true // Set the popin to true to load the form in popin mode
        })
      )
      .then(({ KR }) =>
        KR.addForm("#myPaymentForm")
      ) // Generate the form
      .then(({ KR, result }) =>
        KR.showForm(result.formId)
      ) // Show the form popin button
      .then(({ KR }) =>
        KR.openPopin()
      ) /* Open the popin */
      .then( ({ KR }) => KR.onSubmit(response => this.showPaid(response)))
```

**Comment by HUANGManutea** [comment]
Hi @s-yagues ,
Thank you for your answer, I managed to find the problem, I had a typescript error when I tried your solution, because 'kr-popin' is not defined in the KRConfig interface, so I tried to ignore the typescript error, and it worked !

For anyone looking for the solution, this is my "final code":

```typecript
let KRWrapper = await KRGlue.loadLibrary(endpoint, publicKey) /* Load the remote library */

    let KR = KRWrapper.KR
    
    await KR.setFormConfig({
      /* set the minimal configuration */
      formToken: formTokenResponse.formToken,
      "kr-language": "fr-FR", /* to update initialization parameter */
      // this ignore is important
      // @ts-ignore
      'kr-popin': true,
    })
    //add a payment form  to myPaymentForm div
    let KRWrapperResult = await KR.addForm("#myPaymentForm")
    let result = KRWrapperResult.result

    // show the payment form
    await KR.showForm(result.formId)

    // show the popin
    await KR.openPopin(result.formId);
    console.log("did openpopin");

    await KR.onSubmit(response => this.showPaid(response));
```

**Comment by kevin-dev71** [comment]
how to use popin with attachForm?
