### ISSUE TITLE
Embedded form not working on iOS

### ISSUE THREAD

**Issue by BastienCivel** [lyra/embedded-form-glue#202]
Hello ! 
I use this component in my ionic cordova app using angular. So far it works great on web and Android device, but I cannot make it work on iOS device. The form token is correctly generated, but the pop-in with the card information won't show.
Is there any other configuration that I need to make ?
Thanks in advance !

**Comment by s-yagues** [comment]
Hi @BastienCivel ,

Thanks for reaching in. According to your description, is possible that the issue is that you need to add the tag `allow-navigation` in your `config.xml` for the platform ios with the domain name used to load the JS. e.g:

**Comment by BastienCivel** [comment]
Hi,
Sorry for not coming back to you earlier. That was exactly it !
Thank you :).
