### ISSUE TITLE
Change card logo brand

### ISSUE THREAD

**Issue by NigsonNeves** [lyra/embedded-form-glue#223]
Hi,

Nice to meet you :)

I'm actually trying to see if that possible to change logo brand of each card on the Lyra form (VueJs).

Is there a way of achieving this ?

Thank you very much for your help :)

**Comment by yyoyo** [comment]
Hi.

First of all, sorry for the late answer.

It's not possible to change the card logos. We have to respect mandatory guidelines required by the card brands.

Best Regards,
