### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'DEFAULT')

### ISSUE THREAD

**Issue by Ignusmart** [lyra/embedded-form-glue#257]
Hi Everyone! I'm getting an error using the [NextJS Example](https://github.com/lyra/embedded-form-glue/tree/master/examples/react/next-minimal)

```
next-dev.js?3515:20 TypeError: Cannot read properties of undefined (reading 'DEFAULT')
    at t.value (Reader.js:255:15)
    at t.value (Reader.js:19:9)
    at t.value (DNA.js:26:33)
    at Blender.js:111:17
```

Have anyone ran into this error before?

**Comment by yyoyo** [comment]
Hi.

It's because the shop you are using does not have any card payment attached.

Best Regards.
