### ISSUE TITLE
TypeScript: allow KR.button.onClick callback as Promise<boolean>

### ISSUE THREAD

**Issue by Jordan-T** [lyra/embedded-form-glue#263]
In index.d.ts, the callback can't be a promise but is allowed in the documentation: https://docs.lyra.com/fr/rest/V4.0/javascript/features/kr_onClick.html

**Comment by s-yagues** [comment]
Hi @Jordan-T ,

Thanks for reaching out. Looks like the indes.d.ts is not up to date. We'll update it.

**Comment by s-yagues** [comment]
Hi @Jordan-T ,

An up to date version of `index.d.ts` is available on the latest release `1.3.1`

#270
