### ISSUE TITLE
How to modify the form?

### ISSUE THREAD

**Issue by martinGM05** [lyra/embedded-form-glue#278]
Sorry I have read the documentation but for the use of the library I can not find how to modify the form.

I have already implemented the form but i would like to modify some fields of the form such as deleting the number of installments to pay.

![Screen Shot 2023-02-08 at 14 09 32](https://user-images.githubusercontent.com/63875704/217640143-8f977bee-4395-495e-8a29-7c9449f4f305.png)

I suppose it is in the configuration part but I have not been able to find the specific field to establish that it can only be made with 1 payment. 
![Screen Shot 2023-02-08 at 14 12 15](https://user-images.githubusercontent.com/63875704/217640665-d99f9325-b4b4-4712-a22a-3c381c7bc515.png)

**Comment by s-yagues** [comment]
Hi @martinGM05 ,

Thanks for reaching out. The fields displayed in the form depend of your shop's back-office configuration. There is no way to configure it from this library.

**Comment by yyoyo** [comment]
If your shop does not have any instalments configured server side (inside your merchant backoffice), the fields will be automatically hidden.

Please review your shop configuration.

Regards,
Lionel.
