### ISSUE TITLE
Cannot submit a new payment form after first one succeed

### ISSUE THREAD

**Issue by Julien-Marcou** [lyra/embedded-form-glue#33]
I'm having trouble chaining payment forms within my Angular application (I know its not a common usage).

I create the payment forms following the Angular example :

```typescript
import { Component, ElementRef, OnInit, ViewChild } from "@angular/core";
import KRGlue from '@lyracom/embedded-form-glue';
import { BillingService } from '../core/services/billing.service';

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent implements OnInit {

  @ViewChild('paymentForm', {static: true}) private paymentFormContainer: ElementRef<HTMLElement>;

  private static readonly API_ENDPOINT = 'API_ENDPOINT';
  private static readonly API_KEY = 'API_KEY';

  constructor(private readonly billingService: BillingService) {
  }

  ngOnInit(): void {
    this.initializePaymentForm(true);
  }

  async initializePaymentForm(isFirstPayment: boolean = false): Promise<void> {
    // Reset payment form
    this.paymentFormContainer.nativeElement.classList.add('loading');
    this.paymentFormContainer.nativeElement.querySelector('#payment-form').innerHTML = '';

    // Retrieve payment form's config
    const formConfig: {formToken: string} = isFirstPayment
      ? await this.billingService.getFirstPaymentForm().toPromise()
      : await this.billingService.getSecondPaymentForm().toPromise();

    // Init payment form
    KRGlue.loadLibrary(AppComponent.API_ENDPOINT, AppComponent.API_KEY)
      .then(({KR}) => {
        return KR.setFormConfig({
          formToken: formConfig.formToken,
          'kr-language': 'fr-FR',
        });
      })
      .then(({KR}) => {
        return KR.addForm('#payment-form');
      })
      .then(({KR, result}) => {
        return KR.showForm(result.formId);
      })
      .then(({KR}) => {
        return KR.onFormReady(() => {
          this.paymentFormContainer.nativeElement.classList.remove('loading');
        });
      })
      .then(({KR}) => {
        return KR.onSubmit((response) => {
          if (response.clientAnswer.orderStatus === 'PAID') {
            if (isFirstPayment) {
              this.initializePaymentForm();
            } else {
              console.log('Payment success');
            }
          } else {
            console.error(`Payement status : ${response.clientAnswer.orderStatus}`);
          }
        });
      })
      .then(({KR}) => {
        return KR.onError((error) => {
          console.error(error.errorMessage);
        });
      });
  }

}
```

The loading class on the `paymentFormContainer` is just there to show the user that the form is being generated.

The `billingService` generates two different payment tokens that are correct.

Essentially, what it should do is, after the first payment succeed, the first payment form should get replaced with another payment form, but the second form despite being loaded and displayed correctly, doesn't work at all, clicking on the submit button does nothing (not even showing errors if the inputs are empty).

If I reload the entire Angular application (doing F5), after modifying the code, to load the second payment form instead of the first, it directly works, so the problem has nothing to do with the `billingService.getSecondPaymentForm()`, but actually comes from chaining both of the payment form on the same page.

There is no error in the console, but I can see that the second call to the API_ENDPOINT is never made.
The first time I click on the submit button a POST request is made to `API_ENDPOINT/api-payment/V4/Charge/Public/ProcessPayment` with the correct payload `{formToken: ..., paymentForm: ..., ...}`, which is successfull, but when the second form gets generated, nothing happens when I click the submit button.

Do you know if there is some kind of limitation that could block the user to POST a second payment form from the same page ?

(I'm using the version 0.2.7)

**Comment by monisnap-julien** [comment]
Hello, I'm having the same issue with Vue.js. The workaround we had was to use the `KR.removeForms()` function before destroying the component (`beforeDestroy` hook in Vue.js). Moreover, we also specified `"kr-spa-mode": "true"` in `KR.setFormConfig()`, but it doesn't seems to do anything...

However it doesn't seems to work anymore since few days.

So it would be great if there was a simpler way to clean the whole library when a page is changed or a component is destroyed in **spa mode**.

**Comment by AlexSwtlsk** [comment]
I'm also concerned by this issue with SPA & Vue.JS.
I already had `KR.removeForms(); KR = null` in `beforeDestroy()`  

Workflow
1- i choose `497010XXXXXX0014` token & submit for payment, 
    Payzen form displays '497010XXXXXX0014' CB. I do 'pay' and it works

2- i make a new form payment and choose `497010XXXXXX0055` token, submit it
    Payzen form displays and  `497010XXXXXX0014` is still selected. Submit has no action even though `ProcessPayment`gives a 200

If i refresh my browser between those 2 steps; it works well.

**Comment by AlexSwtlsk** [comment]
@monisnap-julien @Julien-Marcou for your information, Lyra is currently investigating this issue

**Comment by yyoyo** [comment]
> I'm also concerned by this issue with SPA & Vue.JS.
> I already had `KR.removeForms(); KR = null` in `beforeDestroy()`
> 
> Workflow
> 1- i choose `497010XXXXXX0014` token & submit for payment,
> Payzen form displays '497010XXXXXX0014' CB. I do 'pay' and it works
> 
> 2- i make a new form payment and choose `497010XXXXXX0055` token, submit it
> Payzen form displays and `497010XXXXXX0014` is still selected. Submit has no action even though `ProcessPayment`gives a 200
> 
> If i refresh my browser between those 2 steps; it works well.

This issue is solved.
We still are working on the ticket original issue.

**Comment by yyoyo** [comment]
Hi,

It should be fixed in the last version of the embedded form Lyra javascript library (4.0.23)

Let me now if it's fixed for you.

**Comment by Julien-Marcou** [comment]
The debug bar says I'm using the client version `js-4.0.22-14`, is this the expected result ?

I've been able to reproduce it, but eventually figured out that the problem was my fault. :sweat_smile:

I was removing the form added by KRGlue with `this.paymentFormContainer.nativeElement.querySelector('#payment-form').innerHTML = '';` and I believe KRGlue was lost and could not reset properly the form when I was adding a new one because of that.

Without this line I get a warning in the debug bar `WARNING | CLIENT_706 | #payment-form content has been dropped by KR.addForm() call`.
When I inspect the form generated by KRGlue it no longer keeps the previous `kr-form-token` attribute and now has the correct one.
So I guess we can close this issue, thanks for your help :smile:

----------------

Just in case other people encounter the same issue as me, I don't know how I was testing it using my first example, because I now have this error in the console `callback already exist in event onFormReady` (or `callback already exist in event onError`).

So I had to properly rewrite a new test case, here is the new clearer example that works :

```typescript
import { Component, OnInit } from "@angular/core";
import { BillingService } from '../core/services/billing.service';
import KRGlue from '@lyracom/embedded-form-glue';

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent implements OnInit {

  private static readonly API_ENDPOINT = 'API_ENDPOINT';
  private static readonly API_KEY = 'API_KEY';

  constructor(private readonly billingService: BillingService) {
  }

  async ngOnInit(): Promise<void> {
    super.ngOnInit();
    await this.loadPaymentLibrary();
    await this.initializePaymentForm();
  }

  private async loadPaymentLibrary(): Promise<void> {
    // Only load the library one time, so we don't end up with error about callback already existing for onFormReady & onError events
    if (!this.KR) {
      await KRGlue.loadLibrary(AppComponent.API_ENDPOINT, AppComponent.API_KEY).then(async ({KR}) => {

        await KR.setFormConfig({'kr-language': 'fr-FR'});

        KR.onSubmit((response) => {
          console.log(`Form submitted : ${response.formId}`);
          if (response.clientAnswer.orderStatus === 'PAID') {
            console.log('Payment success');

            // Initialize a new payment form after the success
            this.initializePaymentForm();

            return true;
          }
          else {
            console.error(`Payment status : ${response.clientAnswer.orderStatus}`);
            return false;
          }
        });

        KR.onError((error) => {
          console.error(error.errorMessage);
        });

        this.KR = KR;
        console.log('Library loaded');
      });
    }
  }

  private async initializePaymentForm(): Promise<void> {
    // Gets a new token every time
    const formToken = await this.billingService.getPaymentForm().toPromise();

    // Builds the form
    await this.KR.setFormToken(formToken);
    await this.KR.addForm('#payment-form').then(async ({KR, result}) => {
      console.log(`Form added : ${result.formId}`);
      return KR.showForm(result.formId);
    });
  }

}
```

You can also do this using the `removeForms()` method which seems to clean the callbacks so you can re-add them (and also might be better to undestand the code), this would give you something like this :

```typescript
import { Component, OnInit } from "@angular/core";
import { BillingService } from '../core/services/billing.service';
import KRGlue from '@lyracom/embedded-form-glue';

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent implements OnInit {

  private static readonly API_ENDPOINT = 'API_ENDPOINT';
  private static readonly API_KEY = 'API_KEY';

  constructor(private readonly billingService: BillingService) {
  }

  async ngOnInit(): Promise<void> {
    super.ngOnInit();
    await this.loadPaymentLibrary();
    await this.initializePaymentForm();
  }

  private async loadPaymentLibrary(): Promise<void> {
    // Only load the library one time
    if (!this.KR) {
      await KRGlue.loadLibrary(AppComponent.API_ENDPOINT, AppComponent.API_KEY).then(async ({KR}) => {
        await KR.setFormConfig({'kr-language': 'fr-FR'});
        this.KR = KR;
        console.log('Library loaded');
      });
    }
  }

  private async initializePaymentForm(): Promise<void> {
    // Cleans forms
    await this.KR.removeForms();

    // Binds form events
    this.KR.onSubmit((response) => {
      console.log(`Form submitted : ${response.formId}`);
      if (response.clientAnswer.orderStatus === 'PAID') {
        console.log('Payment success');

        // Initialize a new payment form after the success
        this.initializePaymentForm();

        return true;
      }
      else {
        console.error(`Payment status : ${response.clientAnswer.orderStatus}`);
        return false;
      }
    });
    this.KR.onError((error) => {
      console.error(error.errorMessage);
    });

    // Gets a new token every time
    const formToken = await this.billingService.getPaymentForm().toPromise();

    // Builds the form
    await this.KR.setFormToken(formToken);
    await this.KR.addForm('#payment-form').then(async ({KR, result}) => {
      console.log(`Form added : ${result.formId}`);
      return KR.showForm(result.formId);
    });
  }

}
```
