### ISSUE TITLE
Cannot read property 'formId' of undefined on previously working embedded form

### ISSUE THREAD

**Issue by mariobrubio** [lyra/embedded-form-glue#82]
Hey,

I just ran into this issue from nowhere, my form was displaying normally and suddenly it stopped working, apparently, "result" is undefined and thats why is not showing the form

![image](https://user-images.githubusercontent.com/21285099/106937730-1d034280-66ec-11eb-9095-7a26e18e0450.png)

![image](https://user-images.githubusercontent.com/21285099/106937749-2391ba00-66ec-11eb-9bbc-88801222a1ca.png)

Thanks in advance

**Comment by s-yagues** [comment]
Hi @mariobrubio ,

We couldn't reproduce this issue, for our use cases KR.addForm method is always returning `{ KR, result: { formId } }`. 

Could you give us more information about your integration (version, dependencies), instructions on how to reproduce it, or provide a minimal example to reproduce it?

**Comment by mariobrubio** [comment]
Hey @s-yagues thank you for answering.

The form was displaying normally and suddenly it stopped working, we didn't change the code at all.

"@lyracom/embedded-form-glue": "^0.3.3",

`import { useDispatch, useSelector } from "react-redux"
import { actCreatePayment } from "../../../../actions/consumer/payment"
import { useEffect, useState } from "react"
import KRGlue from "@lyracom/embedded-form-glue"
import { paymentSelector } from "../selectors"
import { trackPromise } from "react-promise-tracker"

export const usePayment = (history) => {
  const dispatch = useDispatch()
  const payment = useSelector(paymentSelector)
  const endpoint = "https://api.lyra.com"
  const [showSplash, setShowSplash] = useState(false)
  const [showSplashError, setShowSplashError] = useState(false)
  const [showLoading, setShowLoading] = useState(false)

  useEffect(() => {
    dispatch(actCreatePayment())
  }, [dispatch])

  const goBack = () => {
    setShowSplash(false)
    setShowSplashError(false)
    history.goBack()
  }

  useEffect(() => {
    const asyncFunc = async () => {
      try {
        await trackPromise(
          KRGlue.loadLibrary(
            endpoint,
            payment.publicKey
          ) /* Load the remote library */
            .then(({ KR }) =>
              KR.setFormConfig({
                /* set the minimal configuration */
                formToken: payment.formToken,
                "kr-language": "es-US" /* to update initialization parameter */,
              })
            )
            .then(({ KR }) =>
              KR.addForm("#tcPaymentForm")
            ) /* add a payment form  to myPaymentForm div*/
            .then(({ KR, result }) => KR.showForm(result.formId))
            .then(({ KR }) => {
              KR.onFormReady((ready) => {
                const addLabel = (select, textLabel) => {
                  const refField = document.querySelector(select)
                  const label = document.createElement("p")
                  label.innerHTML = textLabel
                  refField.prepend(label)
                }
                addLabel(".kr-pan", "Número De Tarjeta")
                addLabel(".kr-expiry", "Fecha De Expiración")
                addLabel(".kr-security-code", "CVV O Código De Seguridad")

                const refButton = document.querySelector(".kr-payment-button")
                refButton.addEventListener("click", () => {
                  setShowLoading(true)
                })
              })
              KR.onSubmit((payload) => {
                setShowLoading(false)
                setShowSplash(true)
              })
              KR.onError((error) => {
                setShowLoading(false)
                setShowSplashError(true)
              })
            })
        )
      } catch (e) {
        console.log("error", e)
      }
    }
    asyncFunc()
  }, [payment])

  return { goBack, showSplash, showSplashError, showLoading }
}
`

How to reproduce it... honestly I have no idea, the above is our code snippet

**Comment by cbrunielyra** [comment]
Hi @mariobrubio,

We try to reproduce with your code but it's working on our side. Could you make a merge request on this project with an example that reproduce the issue based on your code

**Comment by s-yagues** [comment]
Couldn't reproduce it. Closing it due to inactivity.
