### ISSUE TITLE
Bad EUR formatting

### ISSUE THREAD

**Issue by pedrosimao** [lyra/embedded-form-glue#96]
Currently your library formats EUR currency like this 1.213,49 € where it should actually be formatted like this 1 213,49 € (no dot between numbers 1 and 2).

I have made a dirty fix for my React code while waiting for your final fix. The dirty fix is the following:

```
fixFrenchPaymentButton() {
    const { totalPrice, intl } = this.props;
    const priceInEur = intl.formatNumber(totalPrice, { maximumFractionDigits: 2 });
    const elements: NodeList = document.querySelectorAll('.kr-payment-button');
    const paymentButton = elements[0].childNodes[0];

    paymentButton.textContent = `PAYER ${priceInEur} €`;
  }
```

Thanks for looking into the issue.

**Comment by cbrunielyra** [comment]
This issue will be fix on next release
